site_name: HYDRA - Hydrophone Data Reduction and Analysiss
site_url: https://github.com/ben-hendricks/ssa-docs/
site_author: Ben Hendricks
site_description: >-
  Documentation for HYDRA (Hydrophone Data Reduction and Analysis).

theme:
  name: material
  palette:
    scheme: slate
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
  features:
    - content.code.select
    - content.code.copy


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

plugins:
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Site'
      add_print_site_banner: true
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true

